#pragma once

#include <SDL.h>

constexpr int IS_KEY_UP_ENUM = 300;

enum class InputEventEnum
{
	W_down = SDL_SCANCODE_W,
	S_down = SDL_SCANCODE_S,
	D_down = SDL_SCANCODE_D,
	A_down = SDL_SCANCODE_A,

	Q_down = SDL_SCANCODE_Q,
	ESC_down = SDL_SCANCODE_ESCAPE,

	W_up = SDL_SCANCODE_W - IS_KEY_UP_ENUM,
	S_up = SDL_SCANCODE_S - IS_KEY_UP_ENUM,
	D_up = SDL_SCANCODE_D - IS_KEY_UP_ENUM,
	A_up = SDL_SCANCODE_A - IS_KEY_UP_ENUM,

	UP_down = SDL_SCANCODE_UP,
	DOWN_down = SDL_SCANCODE_DOWN,
	LEFT_down = SDL_SCANCODE_LEFT,
	RIGHT_down = SDL_SCANCODE_RIGHT,

	QUIT = SDL_QUIT,
	KEYDOWN = SDL_KEYDOWN,
	KEYUP = SDL_KEYUP
};