#pragma once

#include <SDL.h>

constexpr int IS_KEY_UP_ENUM = 300;

enum class InputEventEnum
{
	ESC_down = SDL_SCANCODE_ESCAPE,
	BACKSPACE_down = SDL_SCANCODE_BACKSPACE,
	CTRL_down = SDL_SCANCODE_LCTRL,

	A_down = SDL_SCANCODE_A,
	B_down = SDL_SCANCODE_B,
	C_down = SDL_SCANCODE_C,
	D_down = SDL_SCANCODE_D,
	E_down = SDL_SCANCODE_E,
	F_down = SDL_SCANCODE_F,
	G_down = SDL_SCANCODE_G,
	H_down = SDL_SCANCODE_H,
	I_down = SDL_SCANCODE_I,
	J_down = SDL_SCANCODE_J,
	K_down = SDL_SCANCODE_K,
	L_down = SDL_SCANCODE_L,
	M_down = SDL_SCANCODE_M,
	N_down = SDL_SCANCODE_N,
	O_down = SDL_SCANCODE_O,
	P_down = SDL_SCANCODE_P,
	Q_down = SDL_SCANCODE_Q,
	R_down = SDL_SCANCODE_R,
	S_down = SDL_SCANCODE_S,
	T_down = SDL_SCANCODE_T,
	U_down = SDL_SCANCODE_U,
	V_down = SDL_SCANCODE_V,
	W_down = SDL_SCANCODE_W,
	X_down = SDL_SCANCODE_X,
	Y_down = SDL_SCANCODE_Y,
	Z_down = SDL_SCANCODE_Z,

	down_1 = SDL_SCANCODE_1,
	down_2 = SDL_SCANCODE_2,
	down_3 = SDL_SCANCODE_3,
	down_4 = SDL_SCANCODE_4,
	down_5 = SDL_SCANCODE_5,
	down_6 = SDL_SCANCODE_6,
	down_7 = SDL_SCANCODE_7,
	down_8 = SDL_SCANCODE_8,
	down_9 = SDL_SCANCODE_9,
	down_0 = SDL_SCANCODE_0,
	down_tab = SDL_SCANCODE_TAB,
	down_enter = SDL_SCANCODE_RETURN,

	point_down = SDL_SCANCODE_PERIOD,


	W_up = SDL_SCANCODE_W - IS_KEY_UP_ENUM,
	S_up = SDL_SCANCODE_S - IS_KEY_UP_ENUM,
	D_up = SDL_SCANCODE_D - IS_KEY_UP_ENUM,
	A_up = SDL_SCANCODE_A - IS_KEY_UP_ENUM,
	CTRL_up = SDL_SCANCODE_LCTRL - IS_KEY_UP_ENUM,

	UP_down = SDL_SCANCODE_UP,
	DOWN_down = SDL_SCANCODE_DOWN,
	LEFT_down = SDL_SCANCODE_LEFT,
	RIGHT_down = SDL_SCANCODE_RIGHT,

	SCROLL_DOWN,
	SCROLL_UP,

	SCROLL = SDL_MOUSEWHEEL,
	QUIT = SDL_QUIT,
	KEYDOWN = SDL_KEYDOWN,
	KEYUP = SDL_KEYUP,
};